#!/bin/python3
import random

chars = 'abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%&'
length= input('passwordlength?')
length= int(length)

for d in range(3):
  password =''
  for c in range(length):
    password+= random.choice(chars)
  print(password)
